# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



# Metadata
colour: 9966FF
author: Digital Rift
title: Digital Rift Agency
tagline: Design and Development for eSports
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

  
  
  
#Navigation
baseurl: ""
url: "http://digitalrift.co/"
permalink: /:categories/:slug
paginate: 12
paginate_path: "/projects/page:num/"


#Contact Details
email: hello@digitalrift.co
twitter: RiftCo
discord: oo



# Build settings
markdown: kramdown
minify_html: true
html_press:
  unquoted_attributes: false
  drop_empty_values: false
  strip_crlf: false
  js_minifier_options: false
plugins:
  #- jekyll-feed                 # RSS Feed
  - jekyll-paginate             # Blog Pagination
  - jekyll-seo-tag              # SEO Metadata
  #- jekyll-sitemap              # Sitemap
  #- liquid_reading_time         # Reading Time=
  #- octopress-autoprefixer

  
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "project"
  


# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - sass
   - .scss
   - package-lock.json
   - package.json
   - gulpfile.js