---
pages:
- _posts/2018-05-15-mnm-gaming.md
- _posts/2018-05-12-welcome-to-jekyll.markdown
hide_body: false
is_partial: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - project
  label: Layout
  default: project
- type: include
  template: metadata
  label: Metadata
  name: metadata
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- type: text
  name: client_name
  label: Client Name
- type: text
  label: Project Type
  name: project_type
- type: field_group
  label: Participants
  name: participants
  fields:
  - type: boolean
    name: ollie
    label: Ollie
    default: false
  - type: boolean
    name: tom
    label: Tom
