---
pages:
- _posts/2018-05-12-welcome-to-jekyll.markdown
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: true
  default: project
  config:
    required: true
- type: include
  template: metadata
  label: Metadata
  name: metadata
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- type: text
  name: client_name
  label: Client Name
- type: text
  label: Project Type
  name: project_type
- type: blocks
- type: field_group_list
  label: Team
  name: team
  fields:
  - type: text
    name: name
    label: Name
