---
pages:
- _posts/2018-05-12-welcome-to-jekyll.markdown
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: project
- type: include
  template: metadata
  label: Metadata
  name: metadata
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
